version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    networks:
      - microservices-network
    depends_on:
      - inventory-service
      - invoice-api

networks:
  microservices-network:
    external: true
